# Generated by Django 5.1.1 on 2024-11-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('vacaciones', models.FloatField()),
                ('aguinaldo', models.FloatField()),
                ('septimo', models.FloatField()),
                ('tonelaje', models.FloatField(blank=True, null=True)),
                ('cambio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campaña',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('inss', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Descargue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.FloatField()),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpower.campania')),
            ],
            options={
                'verbose_name': 'Carga tonelaje',
                'verbose_name_plural': 'Carga tonelaje',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpower.campania')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manpower.cargo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpower.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Preliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpower.campania')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpower.cargo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpower.personal')),
            ],
            options={
                'verbose_name': 'Preliminar',
                'verbose_name_plural': 'Preliminar',
            },
        ),
    ]
